name: Update License Year
on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - name: Update License Year Action
        uses: EduardaSRBastos/update-license-year-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
